
server:
  port: 10097

spring:
  application:
    name: ORDER-SERVICE
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/db_order_service
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: none

eureka:
  instance:
    preferred-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:18761/eureka}